package nz.ac.canterbury.seng302.portfolio.model.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import org.hibernate.annotations.GenericGenerator;

/**
 * A generic PortfolioEntity class to be inherited from by anything in the portfolio which has
 *  an autogenerated UUID.
 */
@MappedSuperclass
public abstract class PortfolioEntity {
  @Id
  @GeneratedValue(generator = "UUID")
  @GenericGenerator(name = "UUID", strategy = "uuid2")
  private String id;

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }
}
